#ifndef __MODBUS_SLAVE_DEFINES_H__
#define __MODBUS_SLAVE_DEFINES_H__

#define MODBUS_SLAVE_PROTOCOL_RTU 0
#define MODBUS_SLAVE_PROTOCOL_RTU_OVER_TCP 1
#define MODBUS_SLAVE_PROTOCOL_ASCII 2
#define MODBUS_SLAVE_PROTOCOL_TCP 3

#endif

