#ifndef __MODBUS_SERVER_DEFINES_H__
#define __MODBUS_SERVER_DEFINES_H__

#define MODBUS_SERVER_PROTOCOL_RTU 0
#define MODBUS_SERVER_PROTOCOL_RTU_OVER_TCP 1
#define MODBUS_SERVER_PROTOCOL_ASCII 2
#define MODBUS_SERVER_PROTOCOL_TCP 3

#endif

